// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB_HsKeqDMXzvxqZN0SJyUOAxgQ3Huxq-w',
    appId: '1:47729241769:web:f1160de2a30682f5f143b8',
    messagingSenderId: '47729241769',
    projectId: 'practice-33aa3',
    authDomain: 'practice-33aa3.firebaseapp.com',
    storageBucket: 'practice-33aa3.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAbDR-iQC6mFdEu4g1THWvDBcNz2Od6djc',
    appId: '1:47729241769:android:839b481a7681b94ff143b8',
    messagingSenderId: '47729241769',
    projectId: 'practice-33aa3',
    storageBucket: 'practice-33aa3.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB-nyEeBYBJOJP_OdM9ShVQfv6CpQcZuTY',
    appId: '1:47729241769:ios:aa94b2f3d01d831bf143b8',
    messagingSenderId: '47729241769',
    projectId: 'practice-33aa3',
    storageBucket: 'practice-33aa3.appspot.com',
    iosClientId: '47729241769-b345cnenohgcthsg6vlghlta3foosk9f.apps.googleusercontent.com',
    iosBundleId: 'com.example.greengentem',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB-nyEeBYBJOJP_OdM9ShVQfv6CpQcZuTY',
    appId: '1:47729241769:ios:aa94b2f3d01d831bf143b8',
    messagingSenderId: '47729241769',
    projectId: 'practice-33aa3',
    storageBucket: 'practice-33aa3.appspot.com',
    iosClientId: '47729241769-b345cnenohgcthsg6vlghlta3foosk9f.apps.googleusercontent.com',
    iosBundleId: 'com.example.greengentem',
  );
}
